name: Monthly Job

on:
  schedule:
    - cron: "0 10 1 * *"

jobs:
  call-localhost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Call localhost endpoint
        run: |
          # Ganti localhost:1312 dengan alamat endpoint yang benar
          # ini adalah program untuk pemanggilan endpoint transactions otomatis
          curl -X GET http://localhost:1312/new
